export const getCatalogStoreFakeData = [
  {
    id: "1",
    name: "nombre tienda 1",
    slogan: "slogan tienda 1",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: [
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
    ],
    urlStore: "#",
    isAFavorite: false,
    viewsCount: 10,
    portraitImageUrl: "./../assets/img/store-setup/emptyImage.png",
  },
  {
    id: "2",
    name: "nombre tienda 2",
    slogan: "slogan tienda 2",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "3",
    name: "nombre tienda 3",
    slogan: "slogan tienda 3",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "4",
    name: "nombre tienda 4",
    slogan: "slogan tienda 4",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: [
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
    ],
    urlStore: "#",
    isAFavorite: false,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "5",
    name: "nombre tienda 5",
    slogan: "slogan tienda 5",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "./../../public/assets/common/emptyImage.png",
  },
  {
    id: "6",
    name: "nombre tienda 6",
    slogan: "slogan tienda 6",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: [
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
    ],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "7",
    name: "nombre tienda 7",
    slogan: "slogan tienda 7",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: false,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "8",
    name: "nombre tienda 8",
    slogan: "slogan tienda 8",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "9",
    name: "nombre tienda 9",
    slogan: "slogan tienda 9",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: [
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
      "juguetes",
      "Ropa",
      "Accesorios",
      "Libros",
      "Tecnología",
    ],
    urlStore: "#",
    isAFavorite: false,
    viewsCount: 10,
    portraitImageUrl: "",
  },
  {
    id: "10",
    name: "nombre tienda 10",
    slogan: "slogan tienda 10",
    endingDate: "10-02-2022",
    location: "La Ceja, Antioquia. Colombia",
    storeTags: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlStore: "#",
    isAFavorite: true,
    viewsCount: 10,
    portraitImageUrl: "",
  },
];
