export const getCatalogStoreFakeData = [
  {
    id: "1",
    nombre: "nombre tienda 1",
    slogan: "slogan tienda 1",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: false,
    numeroVistas: 10,
    urlImagenPortadaTienda: "./../assets/img/store-setup/emptyImage.png",
  },
  {
    id: "2",
    nombre: "nombre tienda 2",
    slogan: "slogan tienda 2",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "3",
    nombre: "nombre tienda 3",
    slogan: "slogan tienda 3",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "4",
    nombre: "nombre tienda 4",
    slogan: "slogan tienda 4",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: false,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "5",
    nombre: "nombre tienda 5",
    slogan: "slogan tienda 5",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "6",
    nombre: "nombre tienda 6",
    slogan: "slogan tienda 6",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "7",
    nombre: "nombre tienda 7",
    slogan: "slogan tienda 7",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: false,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "8",
    nombre: "nombre tienda 8",
    slogan: "slogan tienda 8",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "9",
    nombre: "nombre tienda 9",
    slogan: "slogan tienda 9",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: false,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
  {
    id: "10",
    nombre: "nombre tienda 10",
    slogan: "slogan tienda 10",
    fechaCierre: "10-02-2022",
    ubicación: "La Ceja, Antioquia. Colombia",
    etiquetas: ["juguetes", "Ropa", "Accesorios", "Libros", "Tecnología"],
    urlTienda: "#",
    estaEnFavorito: true,
    numeroVistas: 10,
    urlImagenPortadaTienda: "",
  },
];
