const latamCountries = [
  {
    region: "NN",
    name: "País de Nacimiento",
    code: "NN",
    flag: "NN",
    currencyCode: "",
    currencyName: "",
  },
  {
    region: "North America",
    name: "Mexico",
    code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    currencyCode: "MXN",
    currencyName: "Peso Mexicano",
  },
  {
    region: "Central America",
    name: "Belize",
    code: "BZ",
    flag: "https://flagcdn.com/bz.svg",
    currencyCode: "BZD",
    currencyName: "Dolar Beliziano",
  },
  {
    region: "Central America",
    name: "Costa Rica",
    code: "CR",
    flag: "https://flagcdn.com/cr.svg",
    currencyCode: "CRC",
    currencyName: "Costa Rican Colón",
  },
  {
    region: "Central America",
    name: "El Salvador",
    code: "SV",
    flag: "https://flagcdn.com/sv.svg",
    currencyCode: "USD",
    currencyName: "Dolar Americano",
  },
  {
    region: "Central America",
    name: "Guatemala",
    code: "GT",
    flag: "https://flagcdn.com/gt.svg",
    currencyCode: "QTQ",
    currencyName: "Quetzal Guatemalteco",
  },
  {
    region: "Central America",
    name: "Honduras",
    code: "HN",
    flag: "https://flagcdn.com/hn.svg",
    currencyCode: "HNL",
    currencyName: "Lempira Hondureña",
  },
  {
    region: "Central America",
    name: "Nicaragua",
    code: "NI",
    flag: "https://flagcdn.com/ni.svg",
    currencyCode: "NIO",
    currencyName: "Córdoba Nicaragüense",
  },
  {
    region: "Central America",
    name: "Panama",
    code: "PA",
    flag: "https://flagcdn.com/pa.svg",
    currencyCode: "PAB",
    currencyName: "Dolar Americano",
  },
  {
    region: "South America",
    name: "Argentina",
    code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    currencyCode: "ARS",
    currencyName: "Peso Argentino",
  },
  {
    region: "South America",
    name: "Bolivia",
    code: "BO",
    flag: "https://flagcdn.com/bo.svg",
    currencyCode: "BOB",
    currencyName: "Boliviano",
  },
  {
    region: "South America",
    name: "Brazil",
    code: "BR",
    flag: "https://flagcdn.com/br.svg",
    currencyCode: "BRL",
    currencyName: "Real brazileño",
  },
  {
    region: "South America",
    name: "Chile",
    code: "CL",
    flag: "https://flagcdn.com/cl.svg",
    currencyCode: "CLP",
    currencyName: "Peso Chileno",
  },
  {
    region: "South America",
    name: "Colombia",
    code: "CO",
    flag: "https://flagcdn.com/co.svg",
    currencyCode: "COP",
    currencyName: "Peso Colombiano",
  },
  {
    region: "South America",
    name: "Ecuador",
    code: "EC",
    flag: "https://flagcdn.com/ec.svg",
    currencyCode: "ECS",
    currencyName: "Dolar Americano",
  },
  {
    region: "South America",
    name: "Paraguay",
    code: "PY",
    flag: "https://flagcdn.com/py.svg",
    currencyCode: "PYG",
    currencyName: "Guaraní Paraguayo",
  },
  {
    region: "South America",
    name: "Peru",
    code: "PE",
    flag: "https://flagcdn.com/pe.svg",
    currencyCode: "PEN",
    currencyName: "Sol",
  },
  {
    region: "South America",
    name: "Uruguay",
    code: "UY",
    flag: "https://flagcdn.com/uy.svg",
    currencyCode: "UYU",
    currencyName: "Peso Uruguayo",
  },
  {
    region: "South America",
    name: "Venezuela",
    code: "VE",
    flag: "https://flagcdn.com/ve.svg",
    currencyCode: "VEF",
    currencyName: "",
  },
  {
    region: "Caribean",
    name: "República Dominicana",
    code: "DO",
    flag: "https://flagcdn.com/do.svg",
    currencyCode: "DOP",
    currencyName: "Bolívar Venezolano",
  },
  {
    region: "Caribean",
    name: "Puerto Rico",
    code: "PR",
    flag: "https://flagcdn.com/pr.svg",
    currencyCode: "USD",
    currencyName: "Dolar Americano",
  },
];

export default latamCountries;
