const latamCountries = [
  {
    region: "NN",
    name: "País de Nacimiento",
    code: "NN",
    flag: "NN",
    currency: "",
  },
  {
    region: "North America",
    name: "Mexico",
    code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Belize",
    code: "BZ",
    flag: "https://flagcdn.com/bz.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Costa Rica",
    code: "CR",
    flag: "https://flagcdn.com/cr.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "El Salvador",
    code: "SV",
    flag: "https://flagcdn.com/sv.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Guatemala",
    code: "GT",
    flag: "https://flagcdn.com/gt.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Honduras",
    code: "HN",
    flag: "https://flagcdn.com/hn.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Nicaragua",
    code: "NI",
    flag: "https://flagcdn.com/ni.svg",
    currency: "",
  },
  {
    region: "Central America",
    name: "Panama",
    code: "PA",
    flag: "https://flagcdn.com/pa.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Argentina",
    code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Bolivia",
    code: "BO",
    flag: "https://flagcdn.com/bo.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Brazil",
    code: "BR",
    flag: "https://flagcdn.com/br.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Chile",
    code: "CL",
    flag: "https://flagcdn.com/cl.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Colombia",
    code: "CO",
    flag: "https://flagcdn.com/co.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Ecuador",
    code: "EC",
    flag: "https://flagcdn.com/ec.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Paraguay",
    code: "PY",
    flag: "https://flagcdn.com/py.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Peru",
    code: "PE",
    flag: "https://flagcdn.com/pe.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Uruguay",
    code: "UY",
    flag: "https://flagcdn.com/uy.svg",
    currency: "",
  },
  {
    region: "South America",
    name: "Venezuela",
    code: "VE",
    flag: "https://flagcdn.com/ve.svg",
    currency: "",
  },
  {
    region: "Caribean",
    name: "República Dominicana",
    code: "DO",
    flag: "https://flagcdn.com/do.svg",
    currency: "",
  },
  {
    region: "Caribean",
    name: "Puerto Rico",
    code: "PR",
    flag: "https://flagcdn.com/pr.svg",
    currency: "",
  },
];

export default latamCountries;
